# Generated by Django 3.1.2 on 2020-10-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display_image',
            field=models.ImageField(default='static/images/head.jpg', upload_to='images'),
        ),
    ]
