# Generated by Django 3.1.2 on 2020-10-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_display_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[(0, 'EPL'), (1, 'laliga'), (2, 'seria-A'), (3, 'bundesliga')], default=0, max_length=50),
        ),
    ]
