# Generated by Django 3.1.2 on 2020-11-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201115_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='display_image',
            field=models.ImageField(default='static/images/head.jpg', upload_to='static'),
        ),
    ]
