# Generated by Django 3.1.2 on 2020-11-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201115_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='display_image',
            field=models.ImageField(default='images/head.png', upload_to='media/dynamic'),
        ),
    ]
