# Generated by Django 3.1.2 on 2020-11-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201116_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'EPL'), (1, 'laliga'), (2, 'seria-A'), (3, 'bundesliga'), (4, 'league 1')], default='EPL'),
        ),
    ]
